### ISSUE TITLE
Could you please explain what serviceprops is and how to use?

### ISSUE THREAD

**Issue by miked314** [macskas/nagios2json#1]
Hi, 

Could you please explain what serviceprops  is and how to use? 
also not sure what services_visible is? 

{'last_state_change': 1576955818, 'plugin_output': 'CRITICAL: Used_percent was 91.70 %', 'status': 'CRITICAL', 'flags': 1485210, 'hostname': 'xxxxx', 'service': 'Disk Usage C', 'host_alive': 1, 'services_total': 8, 'services_visible': 1, 'duration': 0d 0h 23m 53s'}

**Comment by macskas** [comment]
Hello,
Serviceprops is the integrated display filter in nagios. Its a bitfield
built from the listed vars in the nagios and also on the project's github
page:

SERVICE_SCHEDULED_DOWNTIME               1
SERVICE_NO_SCHEDULED_DOWNTIME            2
SERVICE_STATE_ACKNOWLEDGED               4
SERVICE_STATE_UNACKNOWLEDGED             8
SERVICE_CHECKS_DISABLED                  16
SERVICE_CHECKS_ENABLED                   32
...

SERVICE_HARD_STATE                       262144


etc...

So if you want to display all services if it is not acknowledged and
not in scheduled downtime and only in hardstate. You just use:
1|8|262144 = 1+8+262144 = 262153.
If you dont want to calculate anything you can copypaste filter
directly from the nagios cgi. Cos its using the same.

https://support.nagios.com/forum/viewtopic.php?f=7&t=3092

Services visible:
This means how many service checks are failing on the host. Its useful when
you want to aggregate errors. Lets you have 30 checks for a single host and
all of them are failing. You can do the following:
if (services_total-services_visible) == 0)
aggregate the error messages into a single entry instead of displaying all
the errors. So you can just write host is failing and 30/30 is down for the
specific host.

edited: fix services visible description

**Comment by miked314** [comment]
Thank you ! this makes sense. Again thank you for quick reply and for great script!
